[package]
name = "rus"
version = "0.3.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.35", features = ["full"] }
rand = "0.8"
rusqlite = { version = "0.32", features = ["bundled"] }
bcrypt = "0.15"
jsonwebtoken = "9.2"
chrono = { version = "0.4", features = ["serde"] }
actix-web-httpauth = "0.8"
dotenvy = "0.15"
